[package]
name = "lexopt"
version = "0.5.5"
authors = ["TauYip"]
description = "Minimalist command line parser"
keywords = ["args", "arguments", "cli", "parser", "getopt"]
categories = ["command-line-interface"]
repository = "https://github.com/TauYip/lexopt"
license = "MIT"
readme = "README.md"
edition = "2024"
rust-version = "1.96.0"
exclude = [".github", ".gitignore"]
